name: CI

on:
  push:
    branches: ["main", "ci/cd-configure"]
  pull_request:
    branches: ["main"]
env:
  TEX_FILES: ""
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get latex files
        run: |
          FILES=""
          for file in `find -type f -name "*.tex"`
            do
              if [[ $file != *anki.tex ]]; then
                FILES="${file} ${FILES}"
              fi
            done
            echo "{TEX_FILES}={"${FILES}"}">>$GITHUB_ENV
      - name: Build Documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{env.TEX_FILES}}
          working_directory: latex_sources/
          args: -jobname=my_doc -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          compiler: latexmk
      - name: Upload PDF file
        run: ls -la
